export const stallTypeExample =  [
  { key: '1', text: 'Monthly', value: 1 },
  { key: '2', text: 'Quarterly', value: 2 },
  { key: '3', text: 'Bi-annually', value: 3 },
  { key: '4', text: 'Annually', value: 4 },
];

  export const stallLocationExample = [
    { key: "Abia", text: "Abia", value: "Abia" },
    { key: "Adamawa", text: "Adamawa", value: "Adamawa" },
    { key: "Akwa Ibom", text: "Akwa Ibom", value: "Akwa Ibom" },
    { key: "Anambra", text: "Anambra", value: "Anambra" },
    { key: "Bauchi", text: "Bauchi", value: "Bauchi" },
    { key: "Bayelsa", text: "Bayelsa", value: "Bayelsa" },
    { key: "Benue", text: "Benue", value: "Benue" },
    { key: "Borno", text: "Borno", value: "Borno" },
    { key: "Cross River", text: "Cross River", value: "Cross River" },
    { key: "Delta", text: "Delta", value: "Delta" },
    { key: "Ebonyi", text: "Ebonyi", value: "Ebonyi" },
    { key: "Edo", text: "Edo", value: "Edo" },
    { key: "Ekiti", text: "Ekiti", value: "Ekiti" },
    { key: "Enugu", text: "Enugu", value: "Enugu" },
    { key: "FCT", text: "FCT", value: "FCT" },
    { key: "Gombe", text: "Gombe", value: "Gombe" },
    { key: "Imo", text: "Imo", value: "Imo" },
    { key: "Jigawa", text: "Jigawa", value: "Jigawa" },
    { key: "Kaduna", text: "Kaduna", value: "Kaduna" },
    { key: "Kano", text: "Kano", value: "Kano" },
    { key: "Katsina", text: "Katsina", value: "Katsina" },
    { key: "Kebbi", text: "Kebbi", value: "Kebbi" },
    { key: "Kogi", text: "Kogi", value: "Kogi" },
    { key: "Kwara", text: "Kwara", value: "Kwara" },
    { key: "Lagos", text: "Lagos", value: "Lagos" },
    { key: "Nasarawa", text: "Nasarawa", value: "Nasarawa" },
    { key: "Niger", text: "Niger", value: "Niger" },
    { key: "Ogun", text: "Ogun", value: "Ogun" },
    { key: "Ondo", text: "Ondo", value: "Ondo" },
    { key: "Osun", text: "Osun", value: "Osun" },
    { key: "Oyo", text: "Oyo", value: "Oyo" },
    { key: "Plateau", text: "Plateau", value: "Plateau" },
    { key: "Rivers", text: "Rivers", value: "Rivers" },
    { key: "Sokoto", text: "Sokoto", value: "Sokoto" },
    { key: "Taraba", text: "Taraba", value: "Taraba" },
    { key: "Yobe", text: "Yobe", value: "Yobe" },
    { key: "Zamfara", text: "Zamfara", value: "Zamfara" },
  ];
  

  export const stallMarkets = [
    { key: "Abia1", text: "Abia 1", value: 1 },
    { key: "Abia2", text: "Abia 2", value: 2 },
    { key: "Abia3", text: "Abia 3", value: 3 },
    { key: "Adamawa1", text: "Adamawa 1", value: 1 },
    { key: "Adamawa2", text: "Adamawa 2", value: 2 },
    { key: "Adamawa3", text: "Adamawa 3", value: 3 },
    { key: "Akwa Ibom 1", text: "Akwa Ibom 1", value: 1 },
    { key: "Akwa Ibom 2", text: "Akwa Ibom 2", value: 2 },
    { key: "Akwa Ibom 3", text: "Akwa Ibom 3", value: 3 },
    { key: "Anambra1", text: "Anambra 1", value: 1 },
    { key: "Anambra2", text: "Anambra 2", value: 2 },
    { key: "Anambra3", text: "Anambra 3", value: 3 },
    { key: "Bauchi1", text: "Bauchi 1", value: 1 },
    { key: "Bauchi2", text: "Bauchi 2", value: 2 },
    { key: "Bauchi3", text: "Bauchi 3", value: 3 },
    { key: "Bayelsa1", text: "Bayelsa 1", value: 1 },
    { key: "Bayelsa2", text: "Bayelsa 2", value: 2 },
    { key: "Bayelsa3", text: "Bayelsa 3", value: 3 },
    { key: "Benue1", text: "Benue 1", value: 1 },
    { key: "Benue2", text: "Benue 2", value: 2 },
    { key: "Benue3", text: "Benue 3", value: 3 },
    { key: "Borno1", text: "Borno 1", value: 1 },
    { key: "Borno2", text: "Borno 2", value: 2 },
    { key: "Borno3", text: "Borno 3", value: 3 },
    { key: "Cross River 1", text: "Cross River 1", value: 1 },
    { key: "Cross River 2", text: "Cross River 2", value: 2 },
    { key: "Cross River 3", text: "Cross River 3", value: 3 },
    { key: "Delta1", text: "Delta 1", value: 1 },
    { key: "Delta2", text: "Delta 2", value: 2 },
    { key: "Delta3", text: "Delta 3", value: 3 },
    { key: "Ebonyi1", text: "Ebonyi 1", value: 1 },
    { key: "Ebonyi2", text: "Ebonyi 2", value: 2 },
    { key: "Ebonyi3", text: "Ebonyi 3", value: 3 },
    { key: "Edo1", text: "Edo 1", value: 1 },
    { key: "Edo2", text: "Edo 2", value: 2 },
    { key: "Edo3", text: "Edo 3", value: 3 },
    { key: "Ekiti1", text: "Ekiti 1", value: 1 },
    { key: "Ekiti2", text: "Ekiti 2", value: 2 },
    { key: "Ekiti3", text: "Ekiti 3", value: 3 },
    { key: "Enugu1", text: "Enugu 1", value: 1 },
    { key: "Enugu2", text: "Enugu 2", value: 2 },
    { key: "Enugu3", text: "Enugu 3", value: 3 },
    { key: "FCT1", text: "FCT 1", value: 1 },
    { key: "FCT2", text: "FCT 2", value: 2 },
    { key: "FCT3", text: "FCT 3", value: 3 },
    { key: "Gombe1", text: "Gombe 1", value: 1 },
    { key: "Gombe2", text: "Gombe 2", value: 2 },
    { key: "Gombe3", text: "Gombe 3", value: 3 },
    { key: "Imo1", text: "Imo 1", value: 1 },
    { key: "Imo2", text: "Imo 2", value: 2 },
    { key: "Imo3", text: "Imo 3", value: 3 },
    { key: "Jigawa1", text: "Jigawa 1", value: 1 },
    { key: "Jigawa2", text: "Jigawa 2", value: 2 },
    { key: "Jigawa3", text: "Jigawa 3", value: 3 },
    { key: "Kaduna1", text: "Kaduna 1", value: 1 },
    { key: "Kaduna2", text: "Kaduna 2", value: 2 },
    { key: "Kaduna3", text: "Kaduna 3", value: 3 },
    { key: "Kano1", text: "Kano 1", value: 1 },
    { key: "Kano2", text: "Kano 2", value: 2 },
    { key: "Kano3", text: "Kano 3", value: 3 },
    { key: "Katsina1", text: "Katsina 1", value: 1 },
    { key: "Katsina2", text: "Katsina 2", value: 2 },
    { key: "Katsina3", text: "Katsina 3", value: 3 },
    { key: "Kebbi1", text: "Kebbi 1", value: 1 },
    { key: "Kebbi2", text: "Kebbi 2", value: 2 },
    { key: "Kebbi3", text: "Kebbi 3", value: 3 },
    { key: "Kogi1", text: "Kogi 1", value: 1 },
    { key: "Kogi2", text: "Kogi 2", value: 2 },
    { key: "Kogi3", text: "Kogi 3", value: 3 },
    { key: "Kwara1", text: "Kwara 1", value: 1 },
    { key: "Kwara2", text: "Kwara 2", value: 2 },
    { key: "Kwara3", text: "Kwara 3", value: 3 },
    { key: "Lagos1", text: "Lagos 1", value: 1 },
    { key: "Lagos2", text: "Lagos 2", value: 2 },
    { key: "Lagos3", text: "Lagos 3", value: 3 },
    { key: "Nasarawa1", text: "Nasarawa 1", value: 1 },
    { key: "Nasarawa2", text: "Nasarawa 2", value: 2 },
    { key: "Nasarawa3", text: "Nasarawa 3", value: 3 },
    { key: "Niger1", text: "Niger 1", value: 1 },
    { key: "Niger2", text: "Niger 2", value: 2 },
    { key: "Niger3", text: "Niger 3", value: 3 },
    { key: "Ogun1", text: "Ogun 1", value: 1 },
    { key: "Ogun2", text: "Ogun 2", value: 2 },
    { key: "Ogun3", text: "Ogun 3", value: 3 },
    { key: "Ondo1", text: "Ondo 1", value: 1 },
    { key: "Ondo2", text: "Ondo 2", value: 2 },
    { key: "Ondo3", text: "Ondo 3", value: 3 },
    { key: "Osun1", text: "Osun 1", value: 1 },
    { key: "Osun2", text: "Osun 2", value: 2 },
    { key: "Osun3", text: "Osun 3", value: 3 },
    { key: "Oyo1", text: "Oyo 1", value: 1 },
    { key: "Oyo2", text: "Oyo 2", value: 2 },
    { key: "Oyo3", text: "Oyo 3", value: 3 },
    { key: "Plateau1", text: "Plateau 1", value: 1 },
    { key: "Plateau2", text: "Plateau 2", value: 2 },
    { key: "Plateau3", text: "Plateau 3", value: 3 },
    { key: "Rivers1", text: "Rivers 1", value: 1 },
    { key: "Rivers2", text: "Rivers 2", value: 2 },
    { key: "Rivers3", text: "Rivers 3", value: 3 },
    { key: "Sokoto1", text: "Sokoto 1", value: 1 },
    { key: "Sokoto2", text: "Sokoto 2", value: 2 },
    { key: "Sokoto3", text: "Sokoto 3", value: 3 },
    { key: "Taraba1", text: "Taraba 1", value: 1 },
    { key: "Taraba2", text: "Taraba 2", value: 2 },
    { key: "Taraba3", text: "Taraba 3", value: 3 },
    { key: "Yobe1", text: "Yobe 1", value: 1 },
    { key: "Yobe2", text: "Yobe 2", value: 2 },
    { key: "Yobe3", text: "Yobe 3", value: 3 },
    { key: "Zamfara1", text: "Zamfara 1", value: 1 },
    { key: "Zamfara2", text: "Zamfara 2", value: 2 },
    { key: "Zamfara3", text: "Zamfara 3", value: 3 },
  ];
  
  export const domicileBank = [
    { key: 'gtb', text: 'Guaranty Trust Bank', value: 'Guaranty Trust Bank' },
    { key: 'firstBank', text: 'First Bank Of Nigeria', value: 'First Bank Of Nigeria' },
    { key: 'uba', text: 'United Bank Of Africa', value: 'United Bank Of Africa' },
    // { key: 'gtb', text: 'Guaranty Trust Bank', value: 'Guaranty Trust Bank' },
    // { key: 'gtb', text: 'Guaranty Trust Bank', value: 'Guaranty Trust Bank' },
    // { key: 'gtb', text: 'Guaranty Trust Bank', value: 'Guaranty Trust Bank' },
  ];